### ISSUE TITLE
Import with terraform gives JS error

### ISSUE THREAD

**Issue by doctornkz** [splunk-terraform/terraform-provider-signalfx#95] opened 2019-09-27 19:36 UTC
I have configuration like this:
```
resource "signalfx_dashboard" "EFchYljAIAA" {
  dashboard_group   = "EEGxEOrAAAA"
  name              = "test-alerts-copy"
  description       = ""
  charts_resolution = "default"
  time_range        = "-15m"

  chart {
    chart_id = "${signalfx_heatmap_chart.sfx-EFc2N-4AAAA.id}"
    column   = 3
    row      = 0
    width    = 3
    height   = 1
  }

}
resource "signalfx_heatmap_chart" "sfx-EFc2N-4AAAA" {
  name               = "Load Average"
  description        = "Load Average"
  program_text       = <<EOF
A = data('load.midterm', filter=filter('application_name', '****') and filter('environment', 'production'), extrapolation='zero').publish(label='A')
EOF
}
```
It applied to SFX API without any errors, but I receive empty dashboard without my chart.
In JS console I can see this error:
```
Error: Mismatch between chosen palette and threshold values length!
    at setUIColorByScaleFromVis (eval at 11.module.exports (addScript.js:20), <anonymous>:2579:14)
    at Object.setUIFromVis (eval at 11.module.exports (addScript.js:20), <anonymous>:2793:12)
    at eval (eval at 11.module.exports (addScript.js:20), <anonymous>:2441:21)
    at Array.forEach (<anonymous>)
    at Object.mapFromViz (eval at 11.module.exports (addScript.js:20), <anonymous>:2440:7)
    at convertHeatmapChart (eval at 11.module.exports (addScript.js:20), <anonymous>:2319:46)
    at window.signalviewV2ApiUtils.module.exports (eval at 11.module.exports (addScript.js:20), <anonymous>:2374:15)
    at Object.createConformingModelFromV2 (chartDisplayUtils.js:854)
    at ge (dashboard.js:556)
    at dashboard.js:656 "Possibly unhandled rejection: {}"
```
If I open the JSON file from API with broken dashboards I can see something too long:
```
  "sf_type" : "Dashboard",
  "sf_uiModel" : {
    "version" : 1,
    "widgets" : [ {
      "col" : 3,
      "options" : {
        "chartId" : "EFcmGoSAIAA",
        "chartIndex" : 4280899220442161329,   # <<< HERE
        "id" : 0
      },
      "row" : 0,
      "sizeX" : 3,
      "sizeY" : 1
    } ]
  }

```
Sometimes it is negative, and it means we have incorrect integer type here. 
I don't know how can I change parameters to make it work, as you can see it's really primitive config )

**Comment by doctornkz** [comment] 2019-09-27 19:38
JSON from the workable dashboard
```
"sf_selectedEventOverlays" : [ ],
  "sf_type" : "Dashboard",
  "sf_uiModel" : {
    "version" : 1,
    "widgets" : [ {
      "col" : 3,
      "options" : {
        "chartId" : "EFUGYXbAEAE",
        "chartIndex" : 1569445004366,  # <<< HERE
        "id" : 0
      },
      "row" : 0,
      "sizeX" : 3,
      "sizeY" : 1
    }
```
Negative example:
```
{
      "col" : 4,
      "options" : {
        "chartId" : "EFcwZWlAAAA",
        "chartIndex" : -5766036096619627204,
        "id" : 0
      }
```

**Comment by doctornkz** [comment] 2019-09-27 20:02
Definitely it's not connected with range. I change `heatmap` to `time`  and it works. I think `heatmap` API was changed. Maybe we have must-have parameter for `heatmap` now?

**Comment by doctornkz** [comment] 2019-09-27 20:14
Yes, now colors it's required option for `heatmap`, this config works ok:
```
resource "signalfx_heatmap_chart" "sfx-EFc2N-4AAAA" {
  name               = "Load Average"
  description        = "Load Average"
  program_text       = <<EOF
A = data('load.midterm', filter=filter('application_name', '****') and filter('environment', 'production'), extrapolation='zero').publish(label='A')
EOF
color_range { 
  min_value = 0
  max_value = 100
  color = "#0000ff"
  }
}
```
OMG. Maybe it possible to document it somehow or improve API response if I POST incorrect data. I don't know.

**Comment by doctornkz** [comment] 2019-09-27 21:12
Documentation says https://www.terraform.io/docs/providers/signalfx/r/heatmap_chart.html#color_range

**color_range** - (Optional. Conflicts with color_scale) Values and color for the color range. Example: 
  color_range : { min : 0, max : 100, color : "#0000ff" }. Look at this link.
  min_value - (Optional) The minimum value within the coloring range.
  max_value - (Optional) The maximum value within the coloring range.
  color - (**Required**) The color range to use. The starting hex color value for data values in a heatmap chart. Specify the value as a 6-character hexadecimal value preceded by the '#' character, for example "#ea1849" (grass green).

So, `color` is required, but JSON API gives me : 
```
    "colorBy" : "Range",
    "colorRange" : {
      "color" : null,
      "max" : null,
      "min" : null
    },
```
How it possible?

**Comment by cory-signalfx** [comment] 2019-09-30 14:03
Hey @doctornkz,

I'm not sure I follow the issue you're having now. It looks like in your initial comments you had a heatmap with no color options that generated errors. After reopening, I'm not sure if you're talking about something new or just referring to the old error.

For now I will try and repro the initial error (a heatmap chat with no color being bad) and see what I get!

**Comment by doctornkz** [comment] 2019-09-30 14:11
Sorry, team, I was a bit upset at Friday night with awesome reverse engineering. I can create other issue to separate the problem.

**Comment by cory-signalfx** [comment] 2019-09-30 14:12
No worries! Bugs are frustrating! 🐛

**Comment by cory-signalfx** [comment] 2019-09-30 14:14
For what it's worth I have reproduced the error you initially mentioned!

**Comment by doctornkz** [comment] 2019-09-30 14:23
Just to resume:
- Documentation is not clear around color_range and color_scale
- API doesn't show errors if you pass wrong `heatmap` configuration

**Comment by cory-signalfx** [comment] 2019-09-30 14:46
Ok! PR mentioned above that corrects the failure to detect a missing color config. Can you give me an idea of how to improve the docs? (I added them to the example, for one thing!)

**Comment by doctornkz** [comment] 2019-09-30 15:01
It's a pleasure to work with you, Cory. Thanks a lot! 
About documentation : If I understood you clear - we can use only one type of `heatmap` coloring - range or scale. And we MUST use at least one of them. Right?

**Comment by doctornkz** [comment] 2019-09-30 15:04
My approach - https://github.com/doctornkz/terraform-provider-signalfx/blob/master/website/docs/r/heatmap_chart.html.markdown 
But I am not satisfied, it's terrific example how to disappoint the developer.

**Comment by cory-signalfx** [comment] 2019-09-30 15:32
Likewise, @doctornkz! No problem!

Amusingly I changed my patch just a bit before reading yours and we landed at the same conclusion. [Here is my diff](https://github.com/terraform-providers/terraform-provider-signalfx/pull/96/files?file-filters%5B%5D=.go&file-filters%5B%5D=.md#).

This definitely solves the first problem (bad API + error) and helps the developer if they are reading. I'll merge this and we'll consider this good for now?

**Closed as completed** 2019-09-30 16:28 UTC
Labels: bug

**Comment by doctornkz** [comment] 2019-09-30 21:04
Thank you, Cory! Now I am happy )
