### ISSUE TITLE
Floating point numbers sometimes come back with precision errors

### ISSUE THREAD

**Issue by dmason-atlassian** [splunk-terraform/terraform-provider-signalfx#66] opened 2019-08-28 06:28 UTC
Sometimes the state fetched from remote will have a floating point rounding error, causing the comparison to the local copy to be mismatched, even though it's not, and thus triggers a change. I've noticed this especially on low_watermark configuration for an axis.

**Comment by mattthebig** [comment] 2019-12-06 03:06
I'm also getting this problem, I never have a clean plan after applying, horrible for the developer workflow. @cory-signalfx Any progress on getting that PR merged?

**Comment by cory-signalfx** [comment] 2019-12-06 14:15
Hey @mattthebig, I'm sorry to hear this is interfering with your work. I've not merged this PR mostly because I can't reproduce it and I'm leery of making such a change that isn't reproducible.

I've rebased the PR, could you or @dmason-atlassian perchance try this branch out with the places you are seeing this and report back?

**Comment by cory-signalfx** [comment] 2020-03-16 20:41
This should be fixed in #174!

**Closed as completed** 2020-03-19 14:21 UTC
