### ISSUE TITLE
Perpetual diff for dashboard groups in Terraform plan

### ISSUE THREAD

**Issue by jimmycuadra-stripe** [splunk-terraform/terraform-provider-signalfx#227] opened 2020-07-22 23:18 UTC
Greetings,

We are seeing a few of our dashboard groups failing to converge when running `terraform apply`. The dashboard groups in question show in-place modification that removes a bunch of inline `dashboard`s, but after applying, the same diff shows up on the next plan/apply. I suspected that we might have ended up with some corrupt state in our Terraform state file (possibly from migrating from the old signalform provider) and tried to clean it up manually. I removed the attributes Terraform shows as to be removed from the state file, but it added them back during the next apply and continues to show the same diff.

Included below are the details of one of the affected dashboard groups, with unique identifiers redacted using a `<REDACTED-*>` format.

<details>
<summary>What <code>terraform plan</code> shows</summary>

```
# module.dashboards.signalfx_dashboard_group.compute_group will be updated in-place
~ resource "signalfx_dashboard_group" "compute_group" {
      description = "Compute"
      id          = "<REDACTED-DASHBOARD-GROUP-ID>"
      name        = "Compute"
      teams       = [
          "<REDACTED-TEAM-ID>",
      ]

    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
        - dashboard_id = "<REDACTED-DASHBOARD-ID-1>" -> null

        - variable_override {
            - property         = "<REDACTED-VARIABLE-NAME-1>" -> null
            - values           = [
                - "<REDACTED-VARIABLE-VALUE-1>",
              ] -> null
            - values_suggested = [] -> null
          }
        - variable_override {
            - property         = "<REDACTED-VARIABLE-NAME-2>" -> null
            - values           = [
                - "<REDACTED-VARIABLE-VALUE-2>",
              ] -> null
            - values_suggested = [] -> null
          }
        - variable_override {
            - property         = "<REDACTED-VARIABLE-NAME-3>" -> null
            - values           = [
                - "*",
              ] -> null
            - values_suggested = [] -> null
          }
        - variable_override {
            - property         = "<REDACTED-VARIABLE-NAME-4>" -> null
            - values           = [] -> null
            - values_suggested = [] -> null
          }
        - variable_override {
            - property         = "<REDACTED-VARIABLE-NAME-5>" -> null
            - values           = [
                - "*",
              ] -> null
            - values_suggested = [] -> null
          }
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }
    - dashboard {
      }

    - import_qualifier {
      }
  }
```
</details>

<details>
<summary>The resource's state in Terraform's state file</summary>

```json
{
  "module": "module.dashboards",
  "mode": "managed",
  "type": "signalfx_dashboard_group",
  "name": "compute_group",
  "provider": "provider.signalfx",
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "authorized_writer_teams": null,
        "authorized_writer_users": null,
        "dashboard": [
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": "<REDACTED-DASHBOARD-ID-1>",
            "description_override": "",
            "filter_override": [],
            "name_override": "",
            "variable_override": [
              {
                "property": "<REDACTED-VARIABLE-NAME-1>",
                "values": [
                  "<REDACTED-VARIABLE-VALUE-1>"
                ],
                "values_suggested": []
              },
              {
                "property": "<REDACTED-VARIABLE-NAME-2>",
                "values": [
                  "<REDACTED-VARIABLE-VALUE-2>"
                ],
                "values_suggested": []
              },
              {
                "property": "<REDACTED-VARIABLE-NAME-3>",
                "values": [
                  "*"
                ],
                "values_suggested": []
              },
              {
                "property": "<REDACTED-VARIABLE-NAME-4>",
                "values": [],
                "values_suggested": []
              },
              {
                "property": "<REDACTED-VARIABLE-NAME-5>",
                "values": [
                  "*"
                ],
                "values_suggested": []
              }
            ]
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          },
          {
            "dashboard_id": null,
            "description_override": null,
            "filter_override": null,
            "name_override": null,
            "variable_override": null
          }
        ],
        "description": "Compute",
        "id": "<REDACTED-DASHBOARD-GROUP-ID>",
        "import_qualifier": [],
        "name": "Compute",
        "teams": [
          "<REDACTED-TEAM-ID>"
        ]
      },
      "private": "bnVsbA=="
    }
  ]
}
```
</details>

<details>
<summary>The dashboard group as reported by <code>curl https://api.signalfx.com/v2/dashboardgroup/REDACTED-DASHBOARD-GROUP-ID</code></summary>

```json
{
  "authorizedWriters" : {
    "teams" : [ ],
    "users" : [ ]
  },
  "created" : 1525810637469,
  "creator" : "<REDACTED-CREATOR-ID-1>",
  "dashboardConfigs" : [ {
    "configId" : "<REDACTED-CONFIG-ID-2>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-2>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-3>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-3>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-4>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-4>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-5>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-5>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-6>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-6>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-7>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-7>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-8>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-8>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-9>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-9>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-10>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-10>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-11>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-11>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-12>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-12>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-13>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-13>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-14>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-14>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-15>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-15>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-16>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-16>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-17>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-17>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-18>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-18>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-1>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-1>",
    "descriptionOverride" : null,
    "filtersOverride" : {
      "sources" : [ ],
      "variables" : [ {
        "alias" : "null",
        "applyIfExists" : false,
        "description" : "",
        "preferredSuggestions" : [ ],
        "property" : "<REDACTED-VARIABLE-NAME-1>",
        "replaceOnly" : false,
        "required" : true,
        "restricted" : false,
        "value" : [ "<REDACTED-VARIABLE-VALUE-1>" ]
      }, {
        "alias" : "null",
        "applyIfExists" : false,
        "description" : "",
        "preferredSuggestions" : [ ],
        "property" : "<REDACTED-VARIABLE-NAME-5>",
        "replaceOnly" : false,
        "required" : true,
        "restricted" : false,
        "value" : [ "*" ]
      }, {
        "alias" : "null",
        "applyIfExists" : false,
        "description" : "",
        "preferredSuggestions" : [ ],
        "property" : "<REDACTED-VARIABLE-NAME-4>",
        "replaceOnly" : false,
        "required" : true,
        "restricted" : false,
        "value" : ""
      }, {
        "alias" : "null",
        "applyIfExists" : false,
        "description" : "",
        "preferredSuggestions" : [ ],
        "property" : "<REDACTED-VARIABLE-NAME-3>",
        "replaceOnly" : false,
        "required" : true,
        "restricted" : false,
        "value" : [ "*" ]
      }, {
        "alias" : "null",
        "applyIfExists" : false,
        "description" : "",
        "preferredSuggestions" : [ ],
        "property" : "<REDACTED-VARIABLE-NAME-2>",
        "replaceOnly" : false,
        "required" : true,
        "restricted" : false,
        "value" : [ "<REDACTED-VARIABLE-VALUE-2>" ]
      } ]
    },
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-19>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-19>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-20>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-20>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-21>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-21>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-22>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-22>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-23>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-23>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-24>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-24>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-25>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-25>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-26>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-26>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-27>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-27>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-28>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-28>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-29>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-29>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-30>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-30>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-31>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-31>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-32>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-32>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-33>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-33>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-34>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-34>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-35>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-35>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-36>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-36>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-37>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-37>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-38>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-38>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-39>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-39>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-40>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-40>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-41>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-41>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-42>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-42>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  }, {
    "configId" : "<REDACTED-CONFIG-ID-43>",
    "dashboardId" : "<REDACTED-DASHBOARD-ID-43>",
    "descriptionOverride" : null,
    "filtersOverride" : null,
    "nameOverride" : null
  } ],
  "dashboards" : [ "<REDACTED-DASHBOARD-ID-2>", "<REDACTED-DASHBOARD-ID-3>", "<REDACTED-DASHBOARD-ID-4>", "<REDACTED-DASHBOARD-ID-5>", "<REDACTED-DASHBOARD-ID-6>", "<REDACTED-DASHBOARD-ID-7>", "<REDACTED-DASHBOARD-ID-8>", "<REDACTED-DASHBOARD-ID-9>", "<REDACTED-DASHBOARD-ID-10>", "<REDACTED-DASHBOARD-ID-11>", "<REDACTED-DASHBOARD-ID-12>", "<REDACTED-DASHBOARD-ID-13>", "<REDACTED-DASHBOARD-ID-14>", "<REDACTED-DASHBOARD-ID-15>", "<REDACTED-DASHBOARD-ID-16>", "<REDACTED-DASHBOARD-ID-17>", "<REDACTED-DASHBOARD-ID-18>", "<REDACTED-DASHBOARD-ID-1>", "<REDACTED-DASHBOARD-ID-19>", "<REDACTED-DASHBOARD-ID-20>", "<REDACTED-DASHBOARD-ID-21>", "<REDACTED-DASHBOARD-ID-22>", "<REDACTED-DASHBOARD-ID-23>", "<REDACTED-DASHBOARD-ID-24>", "<REDACTED-DASHBOARD-ID-25>", "<REDACTED-DASHBOARD-ID-26>", "<REDACTED-DASHBOARD-ID-27>", "<REDACTED-DASHBOARD-ID-28>", "<REDACTED-DASHBOARD-ID-29>", "<REDACTED-DASHBOARD-ID-30>", "<REDACTED-DASHBOARD-ID-31>", "<REDACTED-DASHBOARD-ID-32>", "<REDACTED-DASHBOARD-ID-33>", "<REDACTED-DASHBOARD-ID-34>", "<REDACTED-DASHBOARD-ID-35>", "<REDACTED-DASHBOARD-ID-36>", "<REDACTED-DASHBOARD-ID-37>", "<REDACTED-DASHBOARD-ID-38>", "<REDACTED-DASHBOARD-ID-39>", "<REDACTED-DASHBOARD-ID-40>", "<REDACTED-DASHBOARD-ID-41>", "<REDACTED-DASHBOARD-ID-42>", "<REDACTED-DASHBOARD-ID-43>" ],
  "description" : "Compute",
  "email" : null,
  "id" : "<REDACTED-DASHBOARD-GROUP-ID>",
  "importQualifiers" : [ {
    "filters" : [ ],
    "metric" : ""
  } ],
  "lastUpdated" : 1595398139414,
  "lastUpdatedBy" : "<REDACTED-CREATOR-ID-1>",
  "name" : "Compute",
  "teams" : [ "<REDACTED-TEAM-ID>" ]
}
```
</details>

The value `bnVsbA==` that appears for the "private" attribute is a Base64 encoding of the string "null".

Any idea why this is happening and how we can get `terraform apply` to converge the dashboard group to a consistent state? Thank you!

**Comment by cory-signalfx** [comment] 2020-07-23 13:30
Hrm, how perplexing. It's not uncommon to find an argument here or there that causes an unclean plan — usually new ones where I make errors — but this is a whole other thing.

Are the dashboards in question mirrors? That's not a code path I feel has been well exercised, so maybe something lurks there… I will probably proceed with trying that out locally today, but do let me know.

**Comment by cory-signalfx** [comment] 2020-07-23 13:49
Ok, did some stuff locally and everything in mirrors seems ok. Forgive my slow understanding of the diff/state as it's a big one! The raft of empty `dashboard` items is especially confusing. I see there are some overrides lurking in there, which I assume is intentional mirroring.

What's the HCL for this dashboard look like? Maybe there's some bug in how the provider is interpreting that?

**Comment by jimmycuadra-stripe** [comment] 2020-07-24 01:29
Hi Cory, thanks for looking into this!

The HCL for the group itself is very simple:

```hcl
resource "signalfx_dashboard_group" "compute_group" {
  name        = "Compute"
  description = "Compute"
  teams       = ["<REDACTED-DASHBOARD-GROUP-ID>"]
}
```

We have three dashboard groups managed from the same Terraform root module. Two of them exhibit the problem while the third (which I believe is the newest of the three) does not. The one that doesn't exhibit the problem doesn't have a list of dashboards in its Terraform state file representation, which is why I originally suspected I might be able to fix this by just removing that data from the problem dashboard groups in the state file.

Dashboards are added to the group in the usual fashion in HCL. The Terraform root module contains a bunch of files for dashboards in the group that look associate the group like this:

```hcl
resource "signalfx_dashboard" "example_dashboard" {
  name            = "example-dashboard"
  dashboard_group = signalfx_dashboard_group.compute_group.id
  // ...
}
```

Regarding mirror dashboards, I believe at least some of them are mirrored, but not all. I checked the dashboard listed as `<REDACTED-DASHBOARD-ID-1>` (the only one to show any non-null configuration in the big list of dashboards) and it does have a few mirrors. Is there an easy way to determine which dashboards are mirrored, given a list of dashboard IDs, so I don't have to manually check all these via the UI?

If it would be helpful in reproducing the problem to have all of our unredacted state, I could send you data privately. Let me know how I should do this, if so!

**Comment by cory-signalfx** [comment] 2020-07-27 15:57
I noticed that the cURL showed mirrors with no overrides and I don't think I'd tested that so I gave it a whirl. Unfortunately it worked as expected and didn't yield an unclean plan. :(

The dashboard group's entries for `dashboard` should **not** be all nulls. Did you import these groups? Regardless if you remove those entries it might help. I'll try and repro locally by adding them by hand to my own config.

**Comment by cory-signalfx** [comment] 2020-07-27 16:02
Ok, adding a null-full dashboard worked as expected, cleaning up after a plan.

The cURL you showed has a *lot* of mirrors going on. It doesn't even jive with what's in the state file, which is worrying. It seems to be only missing the dashboard id. Let me do some import testing over here.

**Comment by cory-signalfx** [comment] 2020-07-27 16:06
Oops, some of my confusion comes from how mirrors and non-mirrors show up in API responses. Dashboards in a group show up in the `dashboard` section, but have no overrides. That's confusing. The plot thickens on how those even got into the state file.

**Comment by cory-signalfx** [comment] 2020-07-27 16:10
Baaaah, I think I found it @jimmycuadra-stripe. PR coming.

**Comment by cory-signalfx** [comment] 2020-07-27 17:56
OK, now I'm in a pickle.

The underlying API mixes concerns here. Mirrors and dashboard members are in the same field, `dashboardConfigs`, but this only works if the customer is an enterprise customer. Otherwise ye olde `groupId` field is the right way. I have no way of really knowing which is which.

The current code is leaving empty `dashboard` entries when the entry is not a mirror. I'm going to need to think about this…

**Comment by jimmycuadra-stripe** [comment] 2020-08-03 21:00
Hi Cory! I was out on vacation last week so forgive the late response. I appreciate you continuing to look into this! If there's anything I can do to help, please let me know!

**Comment by daviddyball** [comment] 2020-09-14 13:56
Hi all,

I too am seeing similar issues to this, although it's only regarding the `import_qualifier` statements in the HCL:

This is the output of the plan:
```
  # signalfx_dashboard_group.<DASHBOARD-NAME> will be updated in-place
  ~ resource "signalfx_dashboard_group" "<DASHBOARD-NAME>" {
        authorized_writer_teams = [
            "<TEAM-ID-1>",
            "<TEAM-ID-2",
        ]
        id                      = "<DASHBOARD-GROUP-ID"
        name                    = "<DASHBOARD-NAME>"

      - import_qualifier {
        }
    }
```
I imported _all_ of our dashboard groupss using `terraform import signalfx_dashboard_group.<name> <ID>`, so I guess it's a carry-over from that?

The issue is that our CI/CD for applying the Terraform now shows that it constantly needs to be run, even though nothing is actually changing (the `import_qualifier` entries just come back after `apply`).

The strange thing is that this only happened for 6/20 dashboard groups that were imported manually using `terraform import`. Not sure what the differences are though.

**Comment by jrcamp** [comment] 2020-09-14 14:42
@daviddyball can you open a support request so we can look at the exact dashboards? Please include your .tf files there. Thanks!

**Comment by atoulme** [comment] 2024-05-03 00:49
Closing this issue ; the discussion continues over the support request.

**Closed as not planned by atoulme** 2024-05-03 00:49 UTC
Labels: waiting-response
