### ISSUE TITLE
Client timeout when creating dashboards with version 4.19.1

### ISSUE THREAD

**Issue by sguillope** [splunk-terraform/terraform-provider-signalfx#197] opened 2020-04-29 00:48 UTC
After upgrading to `4.19.1`, running `apply` started failing when creating dashboards as the creation would time out (I believe 30 sec).
Here's a sample of the output we're getting (module and dashboard names changed). We can see very long creation times for dashboard resource (normally we get 2-3 sec max) and then a couple of them fails because of the client timeout.
```
module.module_1.signalfx_dashboard.dashboard_1: Still creating... [10s elapsed]
module.module_2.signalfx_dashboard.dashboard_1: Still creating... [20s elapsed]
module.module_3.signalfx_dashboard.dashboard_1: Still creating... [10s elapsed]
module.module_3.signalfx_dashboard.dashboard_2: Still creating... [10s elapsed]
module.module_1.signalfx_dashboard.dashboard_3: Still creating... [10s elapsed]
module.module_3.signalfx_dashboard.dashboard_2: Creation complete after 17s [id=EWuqpJyA4AA]
module.module_1.signalfx_dashboard.dashboard_1: Still creating... [20s elapsed]
module.module_2.signalfx_dashboard.dashboard_1: Still creating... [30s elapsed]
module.module_3.signalfx_dashboard.dashboard_1: Still creating... [20s elapsed]
module.module_1.signalfx_dashboard.dashboard_3: Still creating... [20s elapsed]
module.module_3.signalfx_dashboard.dashboard_1: Creation complete after 24s [id=EWuqRLjA4AA]
module.module_1.signalfx_dashboard.dashboard_1: Creation complete after 27s [id=EWuqCsWA0AA]
module.module_1.signalfx_dashboard.dashboard_3: Still creating... [30s elapsed]

Error: Post "https://api.us1.signalfx.com/v2/dashboard": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  on dashboards/module_1/dashboard_3.tf line 7, in resource "signalfx_dashboard" "dashboard_3":
   7: resource "signalfx_dashboard" "dashboard_3" {

Error: Post "https://api.us1.signalfx.com/v2/dashboard": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  on dashboards/module_2/dashboard_1.tf line 13, in resource "signalfx_dashboard" "dashboard_1":
  13: resource "signalfx_dashboard" "dashboard_1" {
```
Note that it only seems to be affecting the creation time for dashboard resources. Creation of chart resources is fine.

Pinning the version of the provider to `4.19.0` fixes the issue.

**Comment by cory-signalfx** [comment] 2020-04-29 15:45
Hey @sguillope, thanks reporting. I've seen one other report of timeouts in #175 but was unable to reproduce or find any smoking guns.

I've got some new ideas today and plan to have a new release this afternoon for you to try.

**Comment by sguillope** [comment] 2020-04-29 15:52
Great! Let me know if there's any additional details I can provide to help pinpoint the issue.

**Comment by saikrishna547** [comment] 2020-04-29 16:18
I am also facing the same issue and not able to see a successful terraform apply.

**Comment by saikrishna547** [comment] 2020-04-29 16:26
Hi @sguillope, How are you able to use 4.19.1? I think the lastest version is 4.18.6 right?

**Comment by cory-signalfx** [comment] 2020-04-29 16:36
The [latest version](https://github.com/terraform-providers/terraform-provider-signalfx/blob/master/CHANGELOG.md) is 4.19.4, with 4.19.5 on the way for both of you to test, @saikrishna547.

**Comment by saikrishna547** [comment] 2020-04-29 16:54
Okay, thanks @cory-signalfx . Let us know once it is available for us to test.

**Comment by cory-signalfx** [comment] 2020-04-29 17:11
Alright, version 4.19.5 is available. Wanna give it a try @saikrishna547 and @sguillope?

**Comment by sguillope** [comment] 2020-05-02 02:24
Thanks @cory-signalfx for jumping on this. I've tested 4.19.5 and unfortunately with the same result as >= 4.19.1.
Just for completeness here's my terraform config:
```tf
terraform {
  required_version = "~> 0.12.24"
  required_providers {
    signalfx = "4.19.5"
  }
  backend "http" {
    address = "..."
  }
}
```

Happy to send you the trace log by email if you think it can help.

**Comment by saikrishna547** [comment] 2020-05-04 19:15
Hi @cory-signalfx , I do still see the issues  with new provider (4.19.5). I am facing the same error.
<img width="417" alt="Screen Shot 2020-05-04 at 12 16 42 PM" src="https://user-images.githubusercontent.com/44275490/81004385-309e1780-8e01-11ea-9599-9160418fdb31.png">
<img width="912" alt="Screen Shot 2020-05-04 at 12 18 32 PM" src="https://user-images.githubusercontent.com/44275490/81004517-6216e300-8e01-11ea-83d6-b2583d79a492.png">

**Comment by cory-signalfx** [comment] 2020-05-05 18:45
Heads up that I've finally found a way to reproduce this locally!

**Comment by cory-signalfx** [comment] 2020-05-05 19:25
Alright, with some effort I tracked this down to dashboards with a number of charts in the 20+ range. The amount of time that the API takes to make such dashboards causes the timeout to be hit, which creates all sorts of problems.

I'm going to make some changes in #200 that increase the timeout, the file some bugs internally about durations.

**Comment by cory-signalfx** [comment] 2020-05-05 19:58
I've filed an internal ticket and will keep this open for a while, but for anyone who encounters this the upcoming `v4.19.6` will have a 120s default timeout and should extend the horizon of this problem.

If you *still* hit the timeout, this will likely require deleting the charts and recreating them.

**Comment by saikrishna547** [comment] 2020-05-05 20:06
@cory-signalfx , Can i know the ETA for this? Because, This is something needed for us to push some of the code into production.

**Comment by cory-signalfx** [comment] 2020-05-05 20:07
Build has been requested, should be in a few hours. (HashiCorp controls this, not me.)

**Comment by saikrishna547** [comment] 2020-05-05 20:09
Cools thanks :)

**Comment by saikrishna547** [comment] 2020-05-06 16:17
Is v4.19.6 available?

**Comment by cory-signalfx** [comment] 2020-05-06 16:20
Eep, looks like Hashi didn't do the release because I had an error in the Changelog. That's my bad. I've asked them to do it with the fix in place. :)

**Comment by saikrishna547** [comment] 2020-05-06 19:40
let us know once that is released. We will test and let you know.

**Comment by cory-signalfx** [comment] 2020-05-06 21:05
Should be live now!

**Comment by saikrishna547** [comment] 2020-05-11 17:12
Looks like it worked for me on Friday, But will give couple more try's today to see if i see any issues.

**Comment by cory-signalfx** [comment] 2020-05-11 17:12
Yay!

**Comment by saikrishna547** [comment] 2020-05-11 17:16
Actually, Do we really see a much difference in time between each resource creation? I do see a lot difference in the time while applying the terraform

**Comment by cory-signalfx** [comment] 2020-05-11 17:18
Sorry @saikrishna547, what do you mean? The outstanding issue is that dashboard creation is *very* slow. The timeout has been extended to accommodate, but it definitely won't fix the problem until the API's performance is improved by engineering @ SignalFx.

**Comment by sguillope** [comment] 2020-05-13 03:55
I can confirm that it fixes the issue. However obviously it takes quite a bit more time to apply changes for all our dashboards. For that reason, we're sticking to 4.19.0 for now.
Thanks

**Comment by cory-signalfx** [comment] 2020-05-14 14:46
I'm glad this fixes things, but this should not have caused any increase in the duration of these operations. This merely increases the time that the provider will wait for an operation to complete.

In other words, `== 4.19.0` should not change durations versus `> 4.19.0`.

**Comment by saikrishna547** [comment] 2020-05-14 19:11
Yeah but we do see some difference in the operations duration. When we have bunch of resources and this change was something I specially observed with the new provider release.

**Comment by cory-signalfx** [comment] 2020-05-14 19:24
Got it. I'll investigate, but I think we can mark this closed.

**Closed as completed by cory-signalfx** 2020-05-14 19:24 UTC
